### ISSUE TITLE
Language problems

### ISSUE THREAD

**Issue by okmechak** [okmechak/DWNM#5]
from ua version **older posts** button  redirects to en version

when pressing blog on ua version it redirects to "http://localhost:8000/ua/2018/06/cool-cafe/archive/" but should be "http://localhost:8000/ua/archive/"

**Comment by ofcrashbash** [comment]
this one is solved currently.. only **template localization is pending**..

**Comment by okmechak** [comment]
Вирішено використовувати лише україенську мову на сайті
